export const seedData = [
  {
    id: 1,
    name: "Aarav Sharma",
    role: "Frontend Dev",
    location: "Delhi",
    score: 92,
    status: "Active",
  },
  {
    id: 2,
    name: "Isha Gupta",
    role: "Product Designer",
    location: "Bengaluru",
    score: 88,
    status: "Active",
  },
  {
    id: 3,
    name: "Kabir Iyer",
    role: "Backend Dev",
    location: "Chennai",
    score: 76,
    status: "Away",
  },
  {
    id: 4,
    name: "Zoya Khan",
    role: "QA Engineer",
    location: "Pune",
    score: 81,
    status: "Active",
  },
  {
    id: 5,
    name: "Raghav Verma",
    role: "Data Analyst",
    location: "Mumbai",
    score: 67,
    status: "Busy",
  },
  {
    id: 6,
    name: "Meera Nair",
    role: "PM",
    location: "Hyderabad",
    score: 90,
    status: "Active",
  },
  {
    id: 7,
    name: "Tara Singh",
    role: "DevOps",
    location: "Noida",
    score: 73,
    status: "Busy",
  },
  {
    id: 8,
    name: "Arjun Patel",
    role: "ML Engineer",
    location: "Ahmedabad",
    score: 95,
    status: "Active",
  },
  {
    id: 9,
    name: "Simran Kaur",
    role: "UX Researcher",
    location: "Jaipur",
    score: 84,
    status: "Away",
  },
  {
    id: 10,
    name: "Nikhil Rao",
    role: "Security Eng",
    location: "Kochi",
    score: 78,
    status: "Active",
  },
  {
    id: 11,
    name: "Priya Das",
    role: "SRE",
    location: "Kolkata",
    score: 82,
    status: "Active",
  },
  {
    id: 12,
    name: "Vikram Joshi",
    role: "Full‑stack Dev",
    location: "Indore",
    score: 89,
    status: "Busy",
  },
  
];
